[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"

[alias]
xtask = "run --package xtask --"

[target.wasm32-unknown-unknown]
rustflags = [
    '-Zunstable-options',
    '-Cpanic=immediate-abort',
    '--cfg',
    'getrandom_backend="wasm_js"',
]

[build]
rustflags = []
