[target.wasm32-unknown-unknown]
runner = "node ../../scripts/no_std_runner.js"
rustflags = [
    "-Zunstable-options",
    "-Zpanic_abort_tests",
    "-Cpanic=immediate-abort",
    "--cfg",
    "getrandom_backend=\"custom\"",
]

[target.thumbv7em-none-eabihf]
rustflags = [
    "--cfg",
    "getrandom_backend=\"custom\"",
]
