(let ([contract (cons/c real? integer?)])
  (assert! (contract (cons 1 2)))
  (assert! (contract (cons 3 4)))
  (assert! (contract (cons 2 2.0)))
  (assert! (not (contract (cons 2 2.5))))
  (assert! (not (contract (cons 1+1i 2.5))))
  (assert! (not (contract "str")))
  (assert! (not (contract (list 1 2)))))

(let ([contract (cons/c symbol? (listof string?))])
  (assert! (contract '(one "two" "three")))
  (assert! (contract (list 'one "two")))
  (assert! (not (contract (list "one" "two"))))
  (assert! (not (contract '(one two "three")))))
