(define (assert-equal! expected actual)
  (unless (equal? expected actual)
    (error "Expected value" expected "but got" actual)))

(let ([port (open-output-string)])
  (write-string "line" port)
  (write-char #\newline port)
  (newline port)
  (write-char #\λ port)
  (write-char #\space port)
  (write-string "test" port)
  (let* ([str (get-output-string port)]
         [port (open-input-string str)])
    (assert-equal! "line" (read-line port))
    (assert-equal! "" (read-line port))
    (assert-equal! "λ test" (read-line port))
    (assert! (eof-object? (read-line port)))))

(let ([port (open-input-string "abλø")])
  (assert-equal! #\a (peek-char port))
  (assert-equal! (char->integer #\a) (peek-byte port))
  (assert-equal! (char->integer #\a) (read-byte port))
  (assert-equal! #\b (read-char port))
  (assert-equal! #\λ (peek-char port))
  (assert-equal! #xce (peek-byte port)) ; λ is encoded as '(#xce #xbb) in utf-8
  (assert-equal! #\λ (peek-char port))
  (assert-equal! #\λ (read-char port))
  (assert-equal! #\ø (peek-char port))
  (assert-equal! #xc3 (peek-byte port)) ; ø is encoded as '(#xc3 #xb8) in utf-8
  (assert-equal! #\ø (read-char port))
  (assert! (eof-object? (read-char port)))
  (assert! (eof-object? (read-byte port))))

(let ([output-port (open-output-string)]
      [input-port (open-input-string "aλ't one")])
  (parameterize ([current-output-port output-port])
    (display "one")
    (print 'two)
    (write #\3)
    (write-byte (char->integer #\space))
    (write-string "four")
    (write-char #\λ)
    (write-bytes (bytes (char->integer #\a) (char->integer #\b)))
    (newline))
  (assert-equal! "one'two#\\3 fourλab\n" (get-output-string output-port))

  (parameterize ([current-input-port input-port])
    (assert-equal! (char->integer #\a) (peek-byte))
    (assert-equal! #\a (peek-char))
    (assert-equal! (char->integer #\a) (read-byte))
    (assert-equal! #\λ (peek-char))
    (assert-equal! #\λ (read-char))
    (assert-equal! (bytes (char->integer #\') (char->integer #\t)) (read-bytes 2))
    (assert-equal! #x20 (peek-byte))
    (assert-equal! #\space (read-char))
    (assert-equal! "one" (read-line))
    (assert! (eof-object? (read-char)))
    (assert! (eof-object? (read-byte)))))
