(assert! (symbol=? 'abc (string->symbol "abc")))
(assert! (equal? 'abc (string->symbol "abc")))
(assert! (eqv? 'abc (string->symbol "abc")))
(assert! (eq? 'abc (string->symbol "abc")))
(assert! (not (symbol=? 'abc (string->uninterned-symbol "abc"))))
(assert! (equal? 'abc (string->uninterned-symbol "abc")))
(assert! (not (eqv? 'abc (string->uninterned-symbol "abc"))))
(assert! (not (eq? 'abc (string->uninterned-symbol "abc"))))
(assert! (symbol=? 'abc 'abc))
(assert! (equal? 'abc 'abc))
(assert! (eqv? 'abc 'abc))
(assert! (eq? 'abc 'abc))
(assert! (not (symbol=? 'abc (string->symbol "def"))))
(assert! (not (equal? 'abc (string->symbol "def"))))
(assert! (not (eqv? 'abc (string->symbol "def"))))
(assert! (not (eq? 'abc (string->symbol "def"))))
(assert! (not (symbol=? 'abc (string->uninterned-symbol "def"))))
(assert! (not (equal? 'abc (string->uninterned-symbol "def"))))
(assert! (not (eqv? 'abc (string->uninterned-symbol "def"))))
(assert! (not (eq? 'abc (string->uninterned-symbol "def"))))
(assert! (not (symbol=? 'abc 'def)))
(assert! (not (equal? 'abc 'def)))
(assert! (not (eqv? 'abc 'def)))
(assert! (not (eq? 'abc 'def)))
