(#%require-dylib "libsteel_rustls" (only-in
    client-connection
    gz-decode
    tcp-connect
    tcp-reader
    tcp-writer
    tls-reader
    tls-stream
    tls-writer
))
(provide 
    client-connection
    gz-decode
    tcp-connect
    tcp-reader
    tcp-writer
    tls-reader
    tls-stream
    tls-writer
)
