name: No-Std Build

on:
  push:
    branches: ['mwp-no-std-test']
  pull_request:
    branches: ['mwp-no-std-test']
  workflow_dispatch:

jobs:
  no_std:
    name: no_std build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: rust-src
      - name: Install wasm and thumb targets
        run: rustup target add wasm32-unknown-unknown thumbv7em-none-eabihf --toolchain nightly
      - name: Build no_std (wasm)
        run: cargo xtask build wasm
      - name: Build no_std (thumbv7em)
        run: cargo xtask build thumb
